"""
WebSocket ticket store implementations.

Short-lived, single-use opaque tickets are issued via ``POST /api/ws/ticket``
and consumed (atomically) on WebSocket upgrade.  Two implementations are
provided:

``RedisTicketStore``
    Production/dev store backed by Redis.  Uses ``SET … EX`` for TTL-based
    expiry and ``GETDEL`` (Redis 6.2+) for atomic single-use consumption.
    Supports both local Redis (URL-based) and Azure Cache for Redis
    (SSL + managed identity token credential).

``InMemoryTicketStore``
    Dict-backed store for unit tests — no external dependencies required.
    Expiry is checked lazily in ``consume()``.

Use ``get_ticket_store()`` to obtain the singleton instance; it selects the
correct implementation based on the application configuration.  In tests,
patch ``backend.api.websocket.get_ticket_store`` (or the equivalent path) to
inject an ``InMemoryTicketStore``.
"""

from __future__ import annotations

import json
import logging
from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone

from backend.config import get_settings

logger = logging.getLogger(__name__)

# Redis key prefix for ticket entries.
_KEY_PREFIX = "ws:ticket:"

# Default ticket TTL in seconds — must match ``_TICKET_TTL_SECONDS`` in
# ``backend/api/websocket.py``.
_DEFAULT_TTL_SECONDS = 30


# ---------------------------------------------------------------------------
# Abstract base class
# ---------------------------------------------------------------------------


class TicketStore(ABC):
    """Abstract contract for WebSocket ticket storage."""

    @abstractmethod
    async def store(
        self,
        ticket_hash: str,
        user_id: str,
        ttl_seconds: int = _DEFAULT_TTL_SECONDS,
    ) -> None:
        """Persist a single-use ticket linked to *user_id* with a TTL.

        Parameters
        ----------
        ticket_hash:
            The opaque ticket string generated by the issuing endpoint.
        user_id:
            The authenticated user's ID to associate with the ticket.
        ttl_seconds:
            Seconds until the ticket is considered expired.
        """

    @abstractmethod
    async def consume(self, ticket_hash: str) -> str | None:
        """Atomically retrieve and delete a ticket.

        Returns the associated ``user_id`` on success, or ``None`` if the
        ticket does not exist or has expired.  A ticket may only be consumed
        once — subsequent calls for the same *ticket_hash* always return
        ``None``.
        """

    @abstractmethod
    async def close(self) -> None:
        """Release any resources held by this store."""


# ---------------------------------------------------------------------------
# In-memory implementation (tests / no-Redis fallback)
# ---------------------------------------------------------------------------


class InMemoryTicketStore(TicketStore):
    """Dict-backed ticket store — no external dependencies required.

    Intended for unit tests.  ``consume()`` performs a lazy expiry check so
    that expired-but-never-consumed tickets do not grant access.  Call
    ``_evict_expired()`` periodically to free memory held by unredeemed
    expired tickets.
    """

    def __init__(self) -> None:
        self._tickets: dict[str, dict] = {}

    async def store(
        self,
        ticket_hash: str,
        user_id: str,
        ttl_seconds: int = _DEFAULT_TTL_SECONDS,
    ) -> None:
        self._tickets[ticket_hash] = {
            "user_id": user_id,
            "expires_at": datetime.now(timezone.utc) + timedelta(seconds=ttl_seconds),
        }

    async def consume(self, ticket_hash: str) -> str | None:
        entry = self._tickets.pop(ticket_hash, None)
        if entry is None:
            return None
        if entry["expires_at"] < datetime.now(timezone.utc):
            return None
        return entry["user_id"]

    async def close(self) -> None:
        self._tickets.clear()

    def _evict_expired(self) -> int:
        """Remove expired unredeemed tickets and return the count removed.

        This is a maintenance helper called by the background cleanup loop in
        ``backend/api/websocket.py`` to prevent unbounded memory growth.
        """
        now = datetime.now(timezone.utc)
        expired = [k for k, v in self._tickets.items() if v["expires_at"] < now]
        for k in expired:
            self._tickets.pop(k, None)
        return len(expired)


# ---------------------------------------------------------------------------
# Redis implementation (production / dev)
# ---------------------------------------------------------------------------


class RedisTicketStore(TicketStore):
    """Redis-backed ticket store for production and dev environments.

    Uses ``SET … EX`` to write tickets with a server-side TTL so that Redis
    handles expiry automatically.  ``GETDEL`` (Redis 6.2+) provides an atomic
    single-use guarantee — the key is deleted in the same round-trip as the
    read, preventing replay under concurrent requests.

    Two connection modes are supported, controlled by ``settings.redis.mode``:

    ``local`` (default)
        Standard URL connection via ``redis.asyncio.from_url()``.

    ``azure``
        Azure Cache for Redis with SSL and a ``DefaultAzureCredential``
        access-token used as the Redis password.
    """

    def __init__(self, redis_settings) -> None:
        self._settings = redis_settings
        self._redis = None  # lazy initialisation on first use

    async def _get_client(self):
        """Return the Redis client, initialising it on the first call."""
        if self._redis is not None:
            return self._redis

        import redis.asyncio as aioredis  # noqa: PLC0415

        if self._settings.mode == "azure":
            from azure.identity.aio import DefaultAzureCredential  # noqa: PLC0415

            credential = DefaultAzureCredential()
            token = await credential.get_token("https://redis.azure.com/.default")
            self._redis = aioredis.Redis(
                host=self._settings.azure_host,
                port=self._settings.azure_port,
                ssl=self._settings.azure_use_ssl,
                username="",
                password=token.token,
                decode_responses=True,
            )
            logger.debug(
                "RedisTicketStore: connected to Azure Cache for Redis at %s:%s",
                self._settings.azure_host,
                self._settings.azure_port,
            )
        else:
            self._redis = aioredis.from_url(
                self._settings.url,
                decode_responses=True,
            )
            logger.debug(
                "RedisTicketStore: connected to Redis at %s", self._settings.url
            )

        return self._redis

    async def store(
        self,
        ticket_hash: str,
        user_id: str,
        ttl_seconds: int = _DEFAULT_TTL_SECONDS,
    ) -> None:
        client = await self._get_client()
        key = f"{_KEY_PREFIX}{ticket_hash}"
        value = json.dumps({"user_id": user_id})
        await client.set(key, value, ex=ttl_seconds)

    async def consume(self, ticket_hash: str) -> str | None:
        client = await self._get_client()
        key = f"{_KEY_PREFIX}{ticket_hash}"
        raw = await client.getdel(key)
        if raw is None:
            return None
        data = json.loads(raw)
        return data["user_id"]

    async def close(self) -> None:
        if self._redis is not None:
            await self._redis.aclose()
            self._redis = None


# ---------------------------------------------------------------------------
# Singleton factory
# ---------------------------------------------------------------------------

_ticket_store: TicketStore | None = None


def get_ticket_store() -> TicketStore:
    """Return the application-wide ``TicketStore`` singleton.

    Selects the implementation based on ``settings.redis``:

    - ``local`` mode → :class:`RedisTicketStore` connected via
      ``REDIS_URL`` (default ``redis://redis:6379/0``).
    - ``azure`` mode → :class:`RedisTicketStore` connected to Azure Cache
      for Redis with SSL and managed identity token credentials.

    To inject a different implementation in tests, patch this function::

        from backend.infrastructure.ticket_store import InMemoryTicketStore
        with patch("backend.api.websocket.get_ticket_store",
                   return_value=InMemoryTicketStore()):
            ...
    """
    global _ticket_store
    if _ticket_store is None:
        settings = get_settings()
        _ticket_store = RedisTicketStore(settings.redis)
    return _ticket_store
