name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Post plan summary
        uses: actions/github-script@v4
        with:
          script: |
            const body = `### Terraform Plan — \
            \
            ─
            \
            \
            \
            
            \
            `;
            // Your content here
            const issue_comment = context.issue.number
            github.issues.createComment({
              ...context.repo,
              issue_number: issue_comment,
              body
            });
